# -*- coding: utf-8 -*-
"""
Created on Thu Aug  6 2026

@author: flori

OPTIMIZATION DIAGRAMS: Geothermal ORC Power Plant (High-Enthalpy Two-Phase Resource)

Description:
    Diagram script that reads optimal_points.csv (produced by
    HighEnthalpyGeoORC_optimise.py). The diagrams are:

    - The built-in T-s diagrams for the ORC working fluid ("r0")
    - a T-Q diagram for EACH HXs (preheater, both geo evaporators, &
      condenser), via tespy's built-in plot_QT_diagram_matplotlib
    - & a global T-Q diagram: Geofluid, ORC heating (preheater & evaporators),
      ORC cooling (condenser), Air cooling. It's generated by using the states
      "r3" (preheater input), "r4" (preheater output/evaporators inputs via the drum), 
      "r11" (evaporators system output via the drum), and the section profile from 
      TESPy's MovingBoundaryHeatExchanger.
      
Note:
    The model is called and re-solved at optimum for a reason.
    The idea was to code by using as much as possible the TESPy embedded functions.
    Doing it directly in the optimimzation script or 
    exporting all connections results from the optimisation script is certainly possible.
    I export the optimal values and run the a simple solve.design (built in the Model Template script),
    re-computing all the cycle for optimal conditions. 
    
AI USAGE:
    (1) AI advised to replace my for loops with list comprehensions.
    Example:
        
    [_c(model, lb).T.val for lb in ("f6", "f5", "f0")]
    
    Rather than,
    
    resultat = []
    for lb in ("f6", "f5", "f0"):
        resultat.append(_c(model, lb).T.val)
        
   (2) It was helpful to built the labels in T-s diagrams.
    Especially to avoid overlaps.    

"""

import matplotlib.pyplot as plt
import pandas as pd

from tespy.tools import get_plotting_data
from HighEnthalpyGeoORC_Template import HighEnthalpyGeoORC

# Heat exchanger component labels in HighEnthalpyGeoORC_Template
HXs = [
    ("preheater", "Preheater"),
    ("geosteam evaporator", "Geosteam Evaporator"),
    ("geobrine evaporator", "Geobrine Evaporator"),
    ("condenser", "Condenser"),
]

def _c(model, label):
    """ a shorthand to get connections"""
    return model.nw.get_conn(label)

# ------------------------------------------------------------------
# 1. Built-in T-s diagrams (wrapper for the title, axis & units...)
# ------------------------------------------------------------------
def Ts_diagram_annotated(model, connection_label="r0", save_dir="."):
    fluid = model.working_fluid

    # Built-in modeltemplate function in v0.10.2
    fig, ax = model.plot_Ts_diagram_matplotlib(connection_label, save_dir=None)

    # --- Plot labels ---
    ax.set_title(f"T-s Diagram ({fluid})", fontsize=16)
    ax.set_xlabel("Entropy s in J/kg·K", fontsize=14)
    ax.set_ylabel("Temperature T in °C", fontsize=14)
    ax.tick_params(axis="both", which="major", labelsize=12)

    # --- Try to place the "rx" labels on the points ---
    _, points = get_plotting_data(model.nw, connection_label)
    seen_coords = {}
    for label, point in points.items():
        # What if the points are the sames ?
        coord_key = (round(point["s"], 1), round(point["T"], 1))
        
        # Numbers of labels for this point
        count = seen_coords.get(coord_key, 0)
        seen_coords[coord_key] = count + 1

        # Offsets (+12 pt for each labels on the same point)
        offset_x = 6
        offset_y = 6 + (count * 12)

        ax.annotate(
            label, xy=(point["s"], point["T"]), 
            xytext=(offset_x, offset_y), textcoords="offset points",
            fontsize=10, color='red', fontweight="bold", zorder=10001,
            )

    fig.tight_layout()
    if save_dir:
        fig.savefig(f"{save_dir}/Ts_{fluid}.svg", bbox_inches="tight")

    return fig, ax

# -----------------------------------------------------------
# 2. One T-Q diagram per heat exchanger (built-in tespy plot)
# -----------------------------------------------------------
def heat_exchangers_QT(model, save_dir="."):
    fluid = model.working_fluid
    figs = []
    for label, display_name in HXs:
        fig, ax = model.plot_QT_diagram_matplotlib(label, save_dir=None)
        ax.set_title(f"T-Q Diagram: {display_name} ({fluid})", fontsize=16)
        ax.set_ylabel("Temperature in °C", fontsize=14)
        ax.set_xlabel("Cumulative heat transferred in kW", fontsize=14)
        ax.legend(["Hot side", "Cold side"], fontsize=12)
        ax.grid(True, linestyle="--", alpha=0.6)
        ax.tick_params(axis="both", which="major", labelsize=12)
        fig.tight_layout()
        if save_dir:
            safe_label = label.replace(" ", "_")
            fig.savefig(f"{save_dir}/qt_{safe_label}_{fluid}.svg", bbox_inches="tight")
        figs.append((fig, ax))
    return figs


# ------------------------------------------------------------------------
# 3. Global T-Q diagram: Geofluid, ORC heating (preheater & evaporators),
#    ORC cooling (condenser), Air cooling
# ------------------------------------------------------------------------
def Global_QT_diagram(model, ax):
    fluid = model.working_fluid

    # --- preheater & evaporators (TESPy HeatExchanger, 3-point profile) ---
    m_orc = _c(model, "r3").m.val
    h_r3, h_r4, h_r11 = (_c(model, labels).h.val for labels in ("r3", "r4", "r11"))
    Q_pre = m_orc * (h_r4 - h_r3) / 1000        # MW ( kW => /1000)
    Q_evap = m_orc * (h_r11 - h_r4) / 1000      # MW
    Q_total_geo = Q_pre + Q_evap

    Q_orc_pts = [0, Q_pre, Q_total_geo]
    T_orc_pts = [_c(model, labels).T.val for labels in ("r3", "r4", "r11")]

    Q_geo_pts = [0, Q_pre, Q_total_geo]
    T_geo_pts = [_c(model, labels).T.val for labels in ("f6", "f5", "f0")]

    ax.plot(Q_orc_pts, T_orc_pts, "r-o", linewidth=2, label="Working fluid(preheat. & evap.)")
    ax.plot(Q_geo_pts, T_geo_pts, "b-o", linewidth=2, label="Geofluid")

    # --- condenser (TESPy MovingBoundaryHeatExchanger, using the sectioned profile) ---
    condenser = model.nw.get_comp("condenser")
    Q_cond_MW = [q / 1000 for q in condenser.Q_sections.val]   # kW => MW
    T_hot_cond = condenser.T_hot_sections.val                  # °C (working fluid side)
    T_cold_cond = condenser.T_cold_sections.val                # °C (air side)

    ax.plot(Q_cond_MW, T_hot_cond, "m--o", linewidth=2, markersize=4, label="Working fluid (cond.)")
    ax.plot(Q_cond_MW, T_cold_cond, "g--o", linewidth=2, markersize=4, label="Cooling fluid")

    ax.set_xlabel("Heat transferred Q [MW]", fontsize=13)
    ax.set_ylabel("Temperature T [°C]", fontsize=13)
    ax.set_title(f"Global T-Q composite ({fluid})", fontsize=14)
    ax.grid(True, linestyle=":", alpha=0.6)
    ax.legend(fontsize=9)


# -----------------------------------------------------------
# Main to call the MODELTEMPLATE 
# -----------------------------------------------------------

summary_df = pd.read_csv("optimal_points.csv")

for _, row in summary_df.iterrows():

    fluid = row["fluid"]
    print(f"\nRe-solving optimal design point for {fluid} "
          f"(p_evap = {row['p_evap_opt']:.3f} bar)...")

    model = HighEnthalpyGeoORC(
        working_fluid       = fluid,
        cooling_fluid        = row["cooling_fluid"],
        geofluidTemperature = row["T_geo"],
        geofluidFlow        = row["m_geo"],
        geofluidVapour      = row["x_steam"],
        evaporationPressure = row["p_evap_opt"],
        T_amb               = row["T_amb"],
        P_amb               = row["P_amb"],
        dT_cd               = row["dT_cd"],
    )
    # --- Print the re-run results ---
    model.nw.print_results()
    
    # --- built-in single-fluid diagrams ---
    Ts_diagram_annotated(model, "r0", save_dir=".")

    # --- HXs T-Q diagram ---
    heat_exchangers_QT(model, save_dir=".")

    # --- global T-Q diagram ---
    fig, ax = plt.subplots(figsize=(8, 6))
    Global_QT_diagram(model, ax)
    fig.tight_layout()
    fig.savefig(f"./global_QT_{fluid}.svg", bbox_inches="tight")

    plt.show()

print("\nAll diagrams generated.")
